CREATE TABLE IF NOT EXISTS fleets
(
    id          SERIAL PRIMARY KEY,
    name        VARCHAR(255) NOT NULL UNIQUE,
    description TEXT,
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS assets
(
    id         UUID PRIMARY KEY,
    name       VARCHAR(255) NOT NULL UNIQUE,
    type       VARCHAR(50)  NOT NULL CHECK (type IN ('SHIP', 'SUBMARINE', 'AIRCRAFT', 'DRONE', 'GROUND_VEHICLE')),
    status     VARCHAR(50)  NOT NULL CHECK (status IN ('ACTIVE', 'MAINTENANCE', 'INACTIVE')),
    fleet_id   INT REFERENCES fleets (id) ON DELETE SET NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);