CREATE TABLE IF NOT EXISTS assets (
    id UUID PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    type VARCHAR(50) NOT NULL CHECK (type IN ('SHIP', 'SUBMARINE', 'AIRCRAFT', 'DRONE', 'GROUND_VEHICLE')),
    status VARCHAR(50) NOT NULL CHECK (status IN ('ACTIVE', 'MAINTENANCE', 'INACTIVE')),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS fleets (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    description TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS fleet_assets (
    asset_id UUID REFERENCES assets (id) ON DELETE CASCADE,
    fleet_id INT REFERENCES fleets (id) ON DELETE CASCADE,
    PRIMARY KEY (asset_id),
    assigned_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);